"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";
import Link from "next/link";
import { tree } from "next/dist/build/templates/app-page";
import { CartProvider, useCart } from '../context/cartContext.js'
import { Navbar } from "components/Navbar";
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	const [isUser, setIsUser] = useState(false)

	useEffect(() => {
		checkUser()
	}, [])

	const checkUser = async () => {
		const user = localStorage.getItem('user');
		console.log('user', user);
		user ? setIsUser(true) : setIsUser(false);
	}



	return (
		<CartProvider>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>

					<Navbar/>

					{children}

					<footer className="footer bg-neutral text-neutral-content p-10">
						<nav>
							<h6 className="footer-title">Services</h6>
							<a className="link link-hover">Branding</a>
							<a className="link link-hover">Design</a>
							<a className="link link-hover">Marketing</a>
							<a className="link link-hover">Advertisement</a>
						</nav>
						<nav>
							<h6 className="footer-title">Company</h6>
							<a className="link link-hover">About us</a>
							<a className="link link-hover">Contact</a>
							<a className="link link-hover">Jobs</a>
							<a className="link link-hover">Press kit</a>
						</nav>
						<nav>
							<h6 className="footer-title">Legal</h6>
							<a className="link link-hover">Terms of use</a>
							<a className="link link-hover">Privacy policy</a>
							<a className="link link-hover">Cookie policy</a>
						</nav>
					</footer>

				</body>


			</html>
		</CartProvider>
	);
}
